name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Test
        run: go test ./...
      -
        name: Install Goreleaser
        run: curl -sSL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | bash
      -
        name: Release
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
